kind: Service
apiVersion: v1
metadata:
  name: tianen-headless
  namespace: tianen
spec:
  selector:
    deployment: tianen
  clusterIP: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
